# ---------------------------------------------------------------------------
# iteration-if-then1.py
# Created on: Thu Jan 27 2011 09:47:59 AM
#   (generated by ArcGIS/ModelBuilder) and then John Gallo
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()


# Local variables...Try to get the iteration number that the model is on.
IterationNum = "%i%"

#branch depending on iteration number.
if IterationNum=1:
    gp.Addmessage("Iteration number = 1")
    gp.SetParameterAsText(2, "True")
    gp.SetparameterAsTExt(3, "False")
else:
    gp.Addmessage("Iteration number NOT = 1")
    gp.SetParameterAsText(2, "False")
    gp.SetparameterAsTExt(3, "True")



