# ---------------------------------------------------------------------------
# mean_con.py
# Created on: Thu Oct 30 2008 12:55:12 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Check out any necessary licenses
gp.CheckOutExtension("spatial")

# Load required toolboxes...***** This seems to be specific to everyones computer, to an extyent
#  PROBABLE CAUSE OF ERRORS:


#gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Spatial Analyst Tools.tbx")
#gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")

gp.AddToolbox("C:\Program Files (x86)\ArcGIS\ArcToolBox\Toolboxes\Spatial Analyst Tools.tbx")
gp.AddToolbox("C:\Program Files (x86)\ArcGIS\ArcToolBox\Toolboxes\Data Management Tools.tbx")

rasterlocations =  gp.getparameterastext(0) # "D:\GIS\Lorax\LK\Scratch\Connectivity" #
outputraster = gp.getparameterastext(1)  # D:\GIS\Lorax\LK\Scratch\Connectivity\linkages_ext

gp.overwriteoutput = 1

# Local variables...
linkages_raw = rasterlocations+"\\"+"linkages_raw"

# Process: Get Raster Properties...
numMean = gp.GetRasterProperties_management(linkages_raw,"MEAN")
numSTD = gp.GetRasterProperties_management(linkages_raw,"STD")

strsum = str(numMean + numSTD)

print strsum
gp.addmessage("mean + standard deviation is "+strsum)

# Process: Con...
gp.Con_sa(linkages_raw,linkages_raw,outputraster,"","Value < " + strsum)
